version: '3.5'
services:
  postgres:
    image: postgres
    container_name: challenge-franco
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - ./volumes/postgres:/data/postgres
    ports:
      - published: ${POSTGRES_PORT}
        target: ${POSTGRES_PORT}
    networks:
      - data
    restart: unless-stopped
networks:
  data:
    driver: bridge
volumes:
  postgres: